// Code generated by protoc-gen-go. DO NOT EDIT.
// source: MyMessage.proto

package me_piotr_wera

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MyMessage struct {
	Name                 string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Numbers              []int32     `protobuf:"varint,2,rep,packed,name=numbers,proto3" json:"numbers,omitempty"`
	Context              ContextEnum `protobuf:"varint,3,opt,name=context,proto3,enum=me.piotr.wera.ContextEnum" json:"context,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *MyMessage) Reset()         { *m = MyMessage{} }
func (m *MyMessage) String() string { return proto.CompactTextString(m) }
func (*MyMessage) ProtoMessage()    {}
func (*MyMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fc5b4e410c1388e, []int{0}
}

func (m *MyMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MyMessage.Unmarshal(m, b)
}
func (m *MyMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MyMessage.Marshal(b, m, deterministic)
}
func (m *MyMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MyMessage.Merge(m, src)
}
func (m *MyMessage) XXX_Size() int {
	return xxx_messageInfo_MyMessage.Size(m)
}
func (m *MyMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_MyMessage.DiscardUnknown(m)
}

var xxx_messageInfo_MyMessage proto.InternalMessageInfo

func (m *MyMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MyMessage) GetNumbers() []int32 {
	if m != nil {
		return m.Numbers
	}
	return nil
}

func (m *MyMessage) GetContext() ContextEnum {
	if m != nil {
		return m.Context
	}
	return ContextEnum_UNDEFINEX
}

type MyMessageWrapper struct {
	Messages             []*MyMessage `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *MyMessageWrapper) Reset()         { *m = MyMessageWrapper{} }
func (m *MyMessageWrapper) String() string { return proto.CompactTextString(m) }
func (*MyMessageWrapper) ProtoMessage()    {}
func (*MyMessageWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fc5b4e410c1388e, []int{1}
}

func (m *MyMessageWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MyMessageWrapper.Unmarshal(m, b)
}
func (m *MyMessageWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MyMessageWrapper.Marshal(b, m, deterministic)
}
func (m *MyMessageWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MyMessageWrapper.Merge(m, src)
}
func (m *MyMessageWrapper) XXX_Size() int {
	return xxx_messageInfo_MyMessageWrapper.Size(m)
}
func (m *MyMessageWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_MyMessageWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_MyMessageWrapper proto.InternalMessageInfo

func (m *MyMessageWrapper) GetMessages() []*MyMessage {
	if m != nil {
		return m.Messages
	}
	return nil
}

func init() {
	proto.RegisterType((*MyMessage)(nil), "me.piotr.wera.MyMessage")
	proto.RegisterType((*MyMessageWrapper)(nil), "me.piotr.wera.MyMessageWrapper")
}

func init() { proto.RegisterFile("MyMessage.proto", fileDescriptor_0fc5b4e410c1388e) }

var fileDescriptor_0fc5b4e410c1388e = []byte{
	// 180 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xf7, 0xad, 0xf4, 0x4d,
	0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xcd, 0x4d, 0xd5,
	0x2b, 0xc8, 0xcc, 0x2f, 0x29, 0xd2, 0x2b, 0x4f, 0x2d, 0x4a, 0x94, 0x12, 0x74, 0xce, 0xcf, 0x2b,
	0x49, 0xad, 0x28, 0x71, 0xcd, 0x2b, 0xcd, 0x85, 0xa8, 0x50, 0xca, 0xe7, 0xe2, 0x84, 0x6b, 0x12,
	0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3,
	0x85, 0x24, 0xb8, 0xd8, 0xf3, 0x4a, 0x73, 0x93, 0x52, 0x8b, 0x8a, 0x25, 0x98, 0x14, 0x98, 0x35,
	0x58, 0x83, 0x60, 0x5c, 0x21, 0x13, 0x2e, 0xf6, 0x64, 0x88, 0x79, 0x12, 0xcc, 0x0a, 0x8c, 0x1a,
	0x7c, 0x46, 0x52, 0x7a, 0x28, 0xd6, 0xe9, 0x21, 0xd9, 0x16, 0x04, 0x53, 0xaa, 0xe4, 0xc1, 0x25,
	0x00, 0xb7, 0x30, 0xbc, 0x28, 0xb1, 0xa0, 0x20, 0xb5, 0x48, 0xc8, 0x84, 0x8b, 0x23, 0x17, 0x22,
	0x52, 0x2c, 0xc1, 0xa8, 0xc0, 0xac, 0xc1, 0x6d, 0x24, 0x81, 0x66, 0x14, 0x5c, 0x4b, 0x10, 0x5c,
	0x65, 0x12, 0x1b, 0xd8, 0x07, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa0, 0x65, 0x8b, 0xbb,
	0xf6, 0x00, 0x00, 0x00,
}
