// Code generated by protoc-gen-go. DO NOT EDIT.
// source: MyMessage.proto

package me_piotr_wera

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MyMessage struct {
	Name      string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Numbers   []int32              `protobuf:"varint,2,rep,packed,name=numbers,proto3" json:"numbers,omitempty"`
	Context   ContextEnum          `protobuf:"varint,3,opt,name=context,proto3,enum=me.piotr.wera.ContextEnum" json:"context,omitempty"`
	Timestamp *timestamp.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Variant:
	//	*MyMessage_Value1
	//	*MyMessage_Value2
	Variant              isMyMessage_Variant `protobuf_oneof:"variant"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *MyMessage) Reset()         { *m = MyMessage{} }
func (m *MyMessage) String() string { return proto.CompactTextString(m) }
func (*MyMessage) ProtoMessage()    {}
func (*MyMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fc5b4e410c1388e, []int{0}
}

func (m *MyMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MyMessage.Unmarshal(m, b)
}
func (m *MyMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MyMessage.Marshal(b, m, deterministic)
}
func (m *MyMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MyMessage.Merge(m, src)
}
func (m *MyMessage) XXX_Size() int {
	return xxx_messageInfo_MyMessage.Size(m)
}
func (m *MyMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_MyMessage.DiscardUnknown(m)
}

var xxx_messageInfo_MyMessage proto.InternalMessageInfo

func (m *MyMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MyMessage) GetNumbers() []int32 {
	if m != nil {
		return m.Numbers
	}
	return nil
}

func (m *MyMessage) GetContext() ContextEnum {
	if m != nil {
		return m.Context
	}
	return ContextEnum_UNDEFINEX
}

func (m *MyMessage) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type isMyMessage_Variant interface {
	isMyMessage_Variant()
}

type MyMessage_Value1 struct {
	Value1 string `protobuf:"bytes,5,opt,name=value1,proto3,oneof"`
}

type MyMessage_Value2 struct {
	Value2 int32 `protobuf:"varint,6,opt,name=value2,proto3,oneof"`
}

func (*MyMessage_Value1) isMyMessage_Variant() {}

func (*MyMessage_Value2) isMyMessage_Variant() {}

func (m *MyMessage) GetVariant() isMyMessage_Variant {
	if m != nil {
		return m.Variant
	}
	return nil
}

func (m *MyMessage) GetValue1() string {
	if x, ok := m.GetVariant().(*MyMessage_Value1); ok {
		return x.Value1
	}
	return ""
}

func (m *MyMessage) GetValue2() int32 {
	if x, ok := m.GetVariant().(*MyMessage_Value2); ok {
		return x.Value2
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*MyMessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*MyMessage_Value1)(nil),
		(*MyMessage_Value2)(nil),
	}
}

type MyMessageWrapper struct {
	Messages             []*MyMessage `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *MyMessageWrapper) Reset()         { *m = MyMessageWrapper{} }
func (m *MyMessageWrapper) String() string { return proto.CompactTextString(m) }
func (*MyMessageWrapper) ProtoMessage()    {}
func (*MyMessageWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fc5b4e410c1388e, []int{1}
}

func (m *MyMessageWrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MyMessageWrapper.Unmarshal(m, b)
}
func (m *MyMessageWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MyMessageWrapper.Marshal(b, m, deterministic)
}
func (m *MyMessageWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MyMessageWrapper.Merge(m, src)
}
func (m *MyMessageWrapper) XXX_Size() int {
	return xxx_messageInfo_MyMessageWrapper.Size(m)
}
func (m *MyMessageWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_MyMessageWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_MyMessageWrapper proto.InternalMessageInfo

func (m *MyMessageWrapper) GetMessages() []*MyMessage {
	if m != nil {
		return m.Messages
	}
	return nil
}

func init() {
	proto.RegisterType((*MyMessage)(nil), "me.piotr.wera.MyMessage")
	proto.RegisterType((*MyMessageWrapper)(nil), "me.piotr.wera.MyMessageWrapper")
}

func init() { proto.RegisterFile("MyMessage.proto", fileDescriptor_0fc5b4e410c1388e) }

var fileDescriptor_0fc5b4e410c1388e = []byte{
	// 262 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0x3d, 0x4f, 0xc3, 0x30,
	0x10, 0x86, 0x31, 0x69, 0x12, 0xe2, 0x8a, 0x2f, 0x4f, 0xa7, 0x2c, 0x58, 0x9d, 0x3c, 0xb9, 0x22,
	0x74, 0x60, 0x06, 0x21, 0x75, 0xe9, 0x62, 0x21, 0x31, 0x3b, 0xe8, 0x88, 0x22, 0xd5, 0x71, 0xe4,
	0x38, 0x05, 0xfe, 0x31, 0x3f, 0x03, 0x11, 0x13, 0xf3, 0xb1, 0xf9, 0xf5, 0x3d, 0xf6, 0x3d, 0x2f,
	0x3d, 0xdf, 0xbd, 0xef, 0x70, 0x18, 0x74, 0x83, 0xb2, 0x77, 0xd6, 0x5b, 0x76, 0x6a, 0x50, 0xf6,
	0xad, 0xf5, 0x4e, 0xbe, 0xa2, 0xd3, 0xe5, 0xe5, 0xbd, 0xed, 0x3c, 0xbe, 0xf9, 0x87, 0x6e, 0x34,
	0x81, 0x28, 0xaf, 0x1a, 0x6b, 0x9b, 0x3d, 0xae, 0xa7, 0x54, 0x8f, 0x2f, 0x6b, 0xdf, 0x1a, 0x1c,
	0xbc, 0x36, 0x7d, 0x00, 0x56, 0x1f, 0x84, 0x16, 0xf1, 0x5b, 0xc6, 0xe8, 0xa2, 0xd3, 0x06, 0x81,
	0x70, 0x22, 0x0a, 0x35, 0x9d, 0x19, 0xd0, 0xbc, 0x1b, 0x4d, 0x8d, 0x6e, 0x80, 0x63, 0x9e, 0x88,
	0x54, 0xcd, 0x91, 0x6d, 0x68, 0xfe, 0x1c, 0x36, 0x42, 0xc2, 0x89, 0x38, 0xab, 0x4a, 0xf9, 0x47,
	0x48, 0xfe, 0xf2, 0x51, 0x33, 0xca, 0x6e, 0x69, 0x11, 0x25, 0x60, 0xc1, 0x89, 0x58, 0x56, 0xa5,
	0x0c, 0x9a, 0x72, 0xd6, 0x94, 0x8f, 0x33, 0xa1, 0x7e, 0x60, 0x06, 0x34, 0x3b, 0xe8, 0xfd, 0x88,
	0xd7, 0x90, 0x7e, 0xf9, 0x6d, 0x8f, 0xd4, 0x77, 0x8e, 0x93, 0x0a, 0x32, 0x4e, 0x44, 0x1a, 0x27,
	0xd5, 0x5d, 0x41, 0xf3, 0x83, 0x76, 0xad, 0xee, 0xfc, 0x6a, 0x4b, 0x2f, 0x62, 0xd3, 0x27, 0xa7,
	0xfb, 0x1e, 0x1d, 0xdb, 0xd0, 0x13, 0x13, 0x6e, 0x06, 0x20, 0x3c, 0x11, 0xcb, 0x0a, 0xfe, 0x75,
	0x88, 0x4f, 0x54, 0x24, 0xeb, 0x6c, 0xf2, 0xbc, 0xf9, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x04, 0x7b,
	0xa0, 0x0c, 0x91, 0x01, 0x00, 0x00,
}
