// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MyMessage.proto

package me.piotr.wera;

public final class MyMessageOuterClass {
  private MyMessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MyMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:me.piotr.wera.MyMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>repeated int32 numbers = 2;</code>
     * @return A list containing the numbers.
     */
    java.util.List<java.lang.Integer> getNumbersList();
    /**
     * <code>repeated int32 numbers = 2;</code>
     * @return The count of numbers.
     */
    int getNumbersCount();
    /**
     * <code>repeated int32 numbers = 2;</code>
     * @param index The index of the element to return.
     * @return The numbers at the given index.
     */
    int getNumbers(int index);

    /**
     * <code>.me.piotr.wera.ContextEnum context = 3;</code>
     * @return The enum numeric value on the wire for context.
     */
    int getContextValue();
    /**
     * <code>.me.piotr.wera.ContextEnum context = 3;</code>
     * @return The context.
     */
    me.piotr.wera.ContextEnumOuterClass.ContextEnum getContext();

    /**
     * <code>.google.protobuf.Timestamp timestamp = 4;</code>
     * @return Whether the timestamp field is set.
     */
    boolean hasTimestamp();
    /**
     * <code>.google.protobuf.Timestamp timestamp = 4;</code>
     * @return The timestamp.
     */
    com.google.protobuf.Timestamp getTimestamp();
    /**
     * <code>.google.protobuf.Timestamp timestamp = 4;</code>
     */
    com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder();

    /**
     * <code>string value1 = 5;</code>
     * @return The value1.
     */
    java.lang.String getValue1();
    /**
     * <code>string value1 = 5;</code>
     * @return The bytes for value1.
     */
    com.google.protobuf.ByteString
        getValue1Bytes();

    /**
     * <code>int32 value2 = 6;</code>
     * @return The value2.
     */
    int getValue2();

    public me.piotr.wera.MyMessageOuterClass.MyMessage.VariantCase getVariantCase();
  }
  /**
   * Protobuf type {@code me.piotr.wera.MyMessage}
   */
  public  static final class MyMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:me.piotr.wera.MyMessage)
      MyMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MyMessage.newBuilder() to construct.
    private MyMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MyMessage() {
      name_ = "";
      numbers_ = emptyIntList();
      context_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MyMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MyMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                numbers_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              numbers_.addInt(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                numbers_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                numbers_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              context_ = rawValue;
              break;
            }
            case 34: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (timestamp_ != null) {
                subBuilder = timestamp_.toBuilder();
              }
              timestamp_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(timestamp_);
                timestamp_ = subBuilder.buildPartial();
              }

              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();
              variantCase_ = 5;
              variant_ = s;
              break;
            }
            case 48: {
              variantCase_ = 6;
              variant_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          numbers_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.piotr.wera.MyMessageOuterClass.internal_static_me_piotr_wera_MyMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.piotr.wera.MyMessageOuterClass.internal_static_me_piotr_wera_MyMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.piotr.wera.MyMessageOuterClass.MyMessage.class, me.piotr.wera.MyMessageOuterClass.MyMessage.Builder.class);
    }

    private int variantCase_ = 0;
    private java.lang.Object variant_;
    public enum VariantCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      VALUE1(5),
      VALUE2(6),
      VARIANT_NOT_SET(0);
      private final int value;
      private VariantCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static VariantCase valueOf(int value) {
        return forNumber(value);
      }

      public static VariantCase forNumber(int value) {
        switch (value) {
          case 5: return VALUE1;
          case 6: return VALUE2;
          case 0: return VARIANT_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public VariantCase
    getVariantCase() {
      return VariantCase.forNumber(
          variantCase_);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NUMBERS_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.IntList numbers_;
    /**
     * <code>repeated int32 numbers = 2;</code>
     * @return A list containing the numbers.
     */
    public java.util.List<java.lang.Integer>
        getNumbersList() {
      return numbers_;
    }
    /**
     * <code>repeated int32 numbers = 2;</code>
     * @return The count of numbers.
     */
    public int getNumbersCount() {
      return numbers_.size();
    }
    /**
     * <code>repeated int32 numbers = 2;</code>
     * @param index The index of the element to return.
     * @return The numbers at the given index.
     */
    public int getNumbers(int index) {
      return numbers_.getInt(index);
    }
    private int numbersMemoizedSerializedSize = -1;

    public static final int CONTEXT_FIELD_NUMBER = 3;
    private int context_;
    /**
     * <code>.me.piotr.wera.ContextEnum context = 3;</code>
     * @return The enum numeric value on the wire for context.
     */
    public int getContextValue() {
      return context_;
    }
    /**
     * <code>.me.piotr.wera.ContextEnum context = 3;</code>
     * @return The context.
     */
    public me.piotr.wera.ContextEnumOuterClass.ContextEnum getContext() {
      @SuppressWarnings("deprecation")
      me.piotr.wera.ContextEnumOuterClass.ContextEnum result = me.piotr.wera.ContextEnumOuterClass.ContextEnum.valueOf(context_);
      return result == null ? me.piotr.wera.ContextEnumOuterClass.ContextEnum.UNRECOGNIZED : result;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 4;
    private com.google.protobuf.Timestamp timestamp_;
    /**
     * <code>.google.protobuf.Timestamp timestamp = 4;</code>
     * @return Whether the timestamp field is set.
     */
    public boolean hasTimestamp() {
      return timestamp_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 4;</code>
     * @return The timestamp.
     */
    public com.google.protobuf.Timestamp getTimestamp() {
      return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 4;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
      return getTimestamp();
    }

    public static final int VALUE1_FIELD_NUMBER = 5;
    /**
     * <code>string value1 = 5;</code>
     * @return The value1.
     */
    public java.lang.String getValue1() {
      java.lang.Object ref = "";
      if (variantCase_ == 5) {
        ref = variant_;
      }
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (variantCase_ == 5) {
          variant_ = s;
        }
        return s;
      }
    }
    /**
     * <code>string value1 = 5;</code>
     * @return The bytes for value1.
     */
    public com.google.protobuf.ByteString
        getValue1Bytes() {
      java.lang.Object ref = "";
      if (variantCase_ == 5) {
        ref = variant_;
      }
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (variantCase_ == 5) {
          variant_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE2_FIELD_NUMBER = 6;
    /**
     * <code>int32 value2 = 6;</code>
     * @return The value2.
     */
    public int getValue2() {
      if (variantCase_ == 6) {
        return (java.lang.Integer) variant_;
      }
      return 0;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (getNumbersList().size() > 0) {
        output.writeUInt32NoTag(18);
        output.writeUInt32NoTag(numbersMemoizedSerializedSize);
      }
      for (int i = 0; i < numbers_.size(); i++) {
        output.writeInt32NoTag(numbers_.getInt(i));
      }
      if (context_ != me.piotr.wera.ContextEnumOuterClass.ContextEnum.UNDEFINEX.getNumber()) {
        output.writeEnum(3, context_);
      }
      if (timestamp_ != null) {
        output.writeMessage(4, getTimestamp());
      }
      if (variantCase_ == 5) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, variant_);
      }
      if (variantCase_ == 6) {
        output.writeInt32(
            6, (int)((java.lang.Integer) variant_));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < numbers_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(numbers_.getInt(i));
        }
        size += dataSize;
        if (!getNumbersList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        numbersMemoizedSerializedSize = dataSize;
      }
      if (context_ != me.piotr.wera.ContextEnumOuterClass.ContextEnum.UNDEFINEX.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, context_);
      }
      if (timestamp_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getTimestamp());
      }
      if (variantCase_ == 5) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, variant_);
      }
      if (variantCase_ == 6) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(
              6, (int)((java.lang.Integer) variant_));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof me.piotr.wera.MyMessageOuterClass.MyMessage)) {
        return super.equals(obj);
      }
      me.piotr.wera.MyMessageOuterClass.MyMessage other = (me.piotr.wera.MyMessageOuterClass.MyMessage) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (!getNumbersList()
          .equals(other.getNumbersList())) return false;
      if (context_ != other.context_) return false;
      if (hasTimestamp() != other.hasTimestamp()) return false;
      if (hasTimestamp()) {
        if (!getTimestamp()
            .equals(other.getTimestamp())) return false;
      }
      if (!getVariantCase().equals(other.getVariantCase())) return false;
      switch (variantCase_) {
        case 5:
          if (!getValue1()
              .equals(other.getValue1())) return false;
          break;
        case 6:
          if (getValue2()
              != other.getValue2()) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (getNumbersCount() > 0) {
        hash = (37 * hash) + NUMBERS_FIELD_NUMBER;
        hash = (53 * hash) + getNumbersList().hashCode();
      }
      hash = (37 * hash) + CONTEXT_FIELD_NUMBER;
      hash = (53 * hash) + context_;
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + getTimestamp().hashCode();
      }
      switch (variantCase_) {
        case 5:
          hash = (37 * hash) + VALUE1_FIELD_NUMBER;
          hash = (53 * hash) + getValue1().hashCode();
          break;
        case 6:
          hash = (37 * hash) + VALUE2_FIELD_NUMBER;
          hash = (53 * hash) + getValue2();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static me.piotr.wera.MyMessageOuterClass.MyMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.piotr.wera.MyMessageOuterClass.MyMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.piotr.wera.MyMessageOuterClass.MyMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.piotr.wera.MyMessageOuterClass.MyMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.piotr.wera.MyMessageOuterClass.MyMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.piotr.wera.MyMessageOuterClass.MyMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.piotr.wera.MyMessageOuterClass.MyMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.piotr.wera.MyMessageOuterClass.MyMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.piotr.wera.MyMessageOuterClass.MyMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static me.piotr.wera.MyMessageOuterClass.MyMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.piotr.wera.MyMessageOuterClass.MyMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.piotr.wera.MyMessageOuterClass.MyMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(me.piotr.wera.MyMessageOuterClass.MyMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code me.piotr.wera.MyMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:me.piotr.wera.MyMessage)
        me.piotr.wera.MyMessageOuterClass.MyMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return me.piotr.wera.MyMessageOuterClass.internal_static_me_piotr_wera_MyMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return me.piotr.wera.MyMessageOuterClass.internal_static_me_piotr_wera_MyMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                me.piotr.wera.MyMessageOuterClass.MyMessage.class, me.piotr.wera.MyMessageOuterClass.MyMessage.Builder.class);
      }

      // Construct using me.piotr.wera.MyMessageOuterClass.MyMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        numbers_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        context_ = 0;

        if (timestampBuilder_ == null) {
          timestamp_ = null;
        } else {
          timestamp_ = null;
          timestampBuilder_ = null;
        }
        variantCase_ = 0;
        variant_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.piotr.wera.MyMessageOuterClass.internal_static_me_piotr_wera_MyMessage_descriptor;
      }

      @java.lang.Override
      public me.piotr.wera.MyMessageOuterClass.MyMessage getDefaultInstanceForType() {
        return me.piotr.wera.MyMessageOuterClass.MyMessage.getDefaultInstance();
      }

      @java.lang.Override
      public me.piotr.wera.MyMessageOuterClass.MyMessage build() {
        me.piotr.wera.MyMessageOuterClass.MyMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public me.piotr.wera.MyMessageOuterClass.MyMessage buildPartial() {
        me.piotr.wera.MyMessageOuterClass.MyMessage result = new me.piotr.wera.MyMessageOuterClass.MyMessage(this);
        int from_bitField0_ = bitField0_;
        result.name_ = name_;
        if (((bitField0_ & 0x00000001) != 0)) {
          numbers_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.numbers_ = numbers_;
        result.context_ = context_;
        if (timestampBuilder_ == null) {
          result.timestamp_ = timestamp_;
        } else {
          result.timestamp_ = timestampBuilder_.build();
        }
        if (variantCase_ == 5) {
          result.variant_ = variant_;
        }
        if (variantCase_ == 6) {
          result.variant_ = variant_;
        }
        result.variantCase_ = variantCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.piotr.wera.MyMessageOuterClass.MyMessage) {
          return mergeFrom((me.piotr.wera.MyMessageOuterClass.MyMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(me.piotr.wera.MyMessageOuterClass.MyMessage other) {
        if (other == me.piotr.wera.MyMessageOuterClass.MyMessage.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.numbers_.isEmpty()) {
          if (numbers_.isEmpty()) {
            numbers_ = other.numbers_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureNumbersIsMutable();
            numbers_.addAll(other.numbers_);
          }
          onChanged();
        }
        if (other.context_ != 0) {
          setContextValue(other.getContextValue());
        }
        if (other.hasTimestamp()) {
          mergeTimestamp(other.getTimestamp());
        }
        switch (other.getVariantCase()) {
          case VALUE1: {
            variantCase_ = 5;
            variant_ = other.variant_;
            onChanged();
            break;
          }
          case VALUE2: {
            setValue2(other.getValue2());
            break;
          }
          case VARIANT_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        me.piotr.wera.MyMessageOuterClass.MyMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (me.piotr.wera.MyMessageOuterClass.MyMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int variantCase_ = 0;
      private java.lang.Object variant_;
      public VariantCase
          getVariantCase() {
        return VariantCase.forNumber(
            variantCase_);
      }

      public Builder clearVariant() {
        variantCase_ = 0;
        variant_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList numbers_ = emptyIntList();
      private void ensureNumbersIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          numbers_ = mutableCopy(numbers_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 numbers = 2;</code>
       * @return A list containing the numbers.
       */
      public java.util.List<java.lang.Integer>
          getNumbersList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(numbers_) : numbers_;
      }
      /**
       * <code>repeated int32 numbers = 2;</code>
       * @return The count of numbers.
       */
      public int getNumbersCount() {
        return numbers_.size();
      }
      /**
       * <code>repeated int32 numbers = 2;</code>
       * @param index The index of the element to return.
       * @return The numbers at the given index.
       */
      public int getNumbers(int index) {
        return numbers_.getInt(index);
      }
      /**
       * <code>repeated int32 numbers = 2;</code>
       * @param index The index to set the value at.
       * @param value The numbers to set.
       * @return This builder for chaining.
       */
      public Builder setNumbers(
          int index, int value) {
        ensureNumbersIsMutable();
        numbers_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 numbers = 2;</code>
       * @param value The numbers to add.
       * @return This builder for chaining.
       */
      public Builder addNumbers(int value) {
        ensureNumbersIsMutable();
        numbers_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 numbers = 2;</code>
       * @param values The numbers to add.
       * @return This builder for chaining.
       */
      public Builder addAllNumbers(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureNumbersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, numbers_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 numbers = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumbers() {
        numbers_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private int context_ = 0;
      /**
       * <code>.me.piotr.wera.ContextEnum context = 3;</code>
       * @return The enum numeric value on the wire for context.
       */
      public int getContextValue() {
        return context_;
      }
      /**
       * <code>.me.piotr.wera.ContextEnum context = 3;</code>
       * @param value The enum numeric value on the wire for context to set.
       * @return This builder for chaining.
       */
      public Builder setContextValue(int value) {
        context_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.me.piotr.wera.ContextEnum context = 3;</code>
       * @return The context.
       */
      public me.piotr.wera.ContextEnumOuterClass.ContextEnum getContext() {
        @SuppressWarnings("deprecation")
        me.piotr.wera.ContextEnumOuterClass.ContextEnum result = me.piotr.wera.ContextEnumOuterClass.ContextEnum.valueOf(context_);
        return result == null ? me.piotr.wera.ContextEnumOuterClass.ContextEnum.UNRECOGNIZED : result;
      }
      /**
       * <code>.me.piotr.wera.ContextEnum context = 3;</code>
       * @param value The context to set.
       * @return This builder for chaining.
       */
      public Builder setContext(me.piotr.wera.ContextEnumOuterClass.ContextEnum value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        context_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.me.piotr.wera.ContextEnum context = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearContext() {
        
        context_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp timestamp_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timestampBuilder_;
      /**
       * <code>.google.protobuf.Timestamp timestamp = 4;</code>
       * @return Whether the timestamp field is set.
       */
      public boolean hasTimestamp() {
        return timestampBuilder_ != null || timestamp_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 4;</code>
       * @return The timestamp.
       */
      public com.google.protobuf.Timestamp getTimestamp() {
        if (timestampBuilder_ == null) {
          return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
        } else {
          return timestampBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 4;</code>
       */
      public Builder setTimestamp(com.google.protobuf.Timestamp value) {
        if (timestampBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          timestamp_ = value;
          onChanged();
        } else {
          timestampBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 4;</code>
       */
      public Builder setTimestamp(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (timestampBuilder_ == null) {
          timestamp_ = builderForValue.build();
          onChanged();
        } else {
          timestampBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 4;</code>
       */
      public Builder mergeTimestamp(com.google.protobuf.Timestamp value) {
        if (timestampBuilder_ == null) {
          if (timestamp_ != null) {
            timestamp_ =
              com.google.protobuf.Timestamp.newBuilder(timestamp_).mergeFrom(value).buildPartial();
          } else {
            timestamp_ = value;
          }
          onChanged();
        } else {
          timestampBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 4;</code>
       */
      public Builder clearTimestamp() {
        if (timestampBuilder_ == null) {
          timestamp_ = null;
          onChanged();
        } else {
          timestamp_ = null;
          timestampBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 4;</code>
       */
      public com.google.protobuf.Timestamp.Builder getTimestampBuilder() {
        
        onChanged();
        return getTimestampFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 4;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
        if (timestampBuilder_ != null) {
          return timestampBuilder_.getMessageOrBuilder();
        } else {
          return timestamp_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getTimestampFieldBuilder() {
        if (timestampBuilder_ == null) {
          timestampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getTimestamp(),
                  getParentForChildren(),
                  isClean());
          timestamp_ = null;
        }
        return timestampBuilder_;
      }

      /**
       * <code>string value1 = 5;</code>
       * @return The value1.
       */
      public java.lang.String getValue1() {
        java.lang.Object ref = "";
        if (variantCase_ == 5) {
          ref = variant_;
        }
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (variantCase_ == 5) {
            variant_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string value1 = 5;</code>
       * @return The bytes for value1.
       */
      public com.google.protobuf.ByteString
          getValue1Bytes() {
        java.lang.Object ref = "";
        if (variantCase_ == 5) {
          ref = variant_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (variantCase_ == 5) {
            variant_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string value1 = 5;</code>
       * @param value The value1 to set.
       * @return This builder for chaining.
       */
      public Builder setValue1(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  variantCase_ = 5;
        variant_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string value1 = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue1() {
        if (variantCase_ == 5) {
          variantCase_ = 0;
          variant_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <code>string value1 = 5;</code>
       * @param value The bytes for value1 to set.
       * @return This builder for chaining.
       */
      public Builder setValue1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        variantCase_ = 5;
        variant_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>int32 value2 = 6;</code>
       * @return The value2.
       */
      public int getValue2() {
        if (variantCase_ == 6) {
          return (java.lang.Integer) variant_;
        }
        return 0;
      }
      /**
       * <code>int32 value2 = 6;</code>
       * @param value The value2 to set.
       * @return This builder for chaining.
       */
      public Builder setValue2(int value) {
        variantCase_ = 6;
        variant_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 value2 = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue2() {
        if (variantCase_ == 6) {
          variantCase_ = 0;
          variant_ = null;
          onChanged();
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:me.piotr.wera.MyMessage)
    }

    // @@protoc_insertion_point(class_scope:me.piotr.wera.MyMessage)
    private static final me.piotr.wera.MyMessageOuterClass.MyMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new me.piotr.wera.MyMessageOuterClass.MyMessage();
    }

    public static me.piotr.wera.MyMessageOuterClass.MyMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MyMessage>
        PARSER = new com.google.protobuf.AbstractParser<MyMessage>() {
      @java.lang.Override
      public MyMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MyMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MyMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MyMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public me.piotr.wera.MyMessageOuterClass.MyMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MyMessageWrapperOrBuilder extends
      // @@protoc_insertion_point(interface_extends:me.piotr.wera.MyMessageWrapper)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .me.piotr.wera.MyMessage messages = 1;</code>
     */
    java.util.List<me.piotr.wera.MyMessageOuterClass.MyMessage> 
        getMessagesList();
    /**
     * <code>repeated .me.piotr.wera.MyMessage messages = 1;</code>
     */
    me.piotr.wera.MyMessageOuterClass.MyMessage getMessages(int index);
    /**
     * <code>repeated .me.piotr.wera.MyMessage messages = 1;</code>
     */
    int getMessagesCount();
    /**
     * <code>repeated .me.piotr.wera.MyMessage messages = 1;</code>
     */
    java.util.List<? extends me.piotr.wera.MyMessageOuterClass.MyMessageOrBuilder> 
        getMessagesOrBuilderList();
    /**
     * <code>repeated .me.piotr.wera.MyMessage messages = 1;</code>
     */
    me.piotr.wera.MyMessageOuterClass.MyMessageOrBuilder getMessagesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code me.piotr.wera.MyMessageWrapper}
   */
  public  static final class MyMessageWrapper extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:me.piotr.wera.MyMessageWrapper)
      MyMessageWrapperOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MyMessageWrapper.newBuilder() to construct.
    private MyMessageWrapper(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MyMessageWrapper() {
      messages_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MyMessageWrapper();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MyMessageWrapper(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                messages_ = new java.util.ArrayList<me.piotr.wera.MyMessageOuterClass.MyMessage>();
                mutable_bitField0_ |= 0x00000001;
              }
              messages_.add(
                  input.readMessage(me.piotr.wera.MyMessageOuterClass.MyMessage.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          messages_ = java.util.Collections.unmodifiableList(messages_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.piotr.wera.MyMessageOuterClass.internal_static_me_piotr_wera_MyMessageWrapper_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.piotr.wera.MyMessageOuterClass.internal_static_me_piotr_wera_MyMessageWrapper_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.piotr.wera.MyMessageOuterClass.MyMessageWrapper.class, me.piotr.wera.MyMessageOuterClass.MyMessageWrapper.Builder.class);
    }

    public static final int MESSAGES_FIELD_NUMBER = 1;
    private java.util.List<me.piotr.wera.MyMessageOuterClass.MyMessage> messages_;
    /**
     * <code>repeated .me.piotr.wera.MyMessage messages = 1;</code>
     */
    public java.util.List<me.piotr.wera.MyMessageOuterClass.MyMessage> getMessagesList() {
      return messages_;
    }
    /**
     * <code>repeated .me.piotr.wera.MyMessage messages = 1;</code>
     */
    public java.util.List<? extends me.piotr.wera.MyMessageOuterClass.MyMessageOrBuilder> 
        getMessagesOrBuilderList() {
      return messages_;
    }
    /**
     * <code>repeated .me.piotr.wera.MyMessage messages = 1;</code>
     */
    public int getMessagesCount() {
      return messages_.size();
    }
    /**
     * <code>repeated .me.piotr.wera.MyMessage messages = 1;</code>
     */
    public me.piotr.wera.MyMessageOuterClass.MyMessage getMessages(int index) {
      return messages_.get(index);
    }
    /**
     * <code>repeated .me.piotr.wera.MyMessage messages = 1;</code>
     */
    public me.piotr.wera.MyMessageOuterClass.MyMessageOrBuilder getMessagesOrBuilder(
        int index) {
      return messages_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < messages_.size(); i++) {
        output.writeMessage(1, messages_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < messages_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, messages_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof me.piotr.wera.MyMessageOuterClass.MyMessageWrapper)) {
        return super.equals(obj);
      }
      me.piotr.wera.MyMessageOuterClass.MyMessageWrapper other = (me.piotr.wera.MyMessageOuterClass.MyMessageWrapper) obj;

      if (!getMessagesList()
          .equals(other.getMessagesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getMessagesCount() > 0) {
        hash = (37 * hash) + MESSAGES_FIELD_NUMBER;
        hash = (53 * hash) + getMessagesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static me.piotr.wera.MyMessageOuterClass.MyMessageWrapper parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.piotr.wera.MyMessageOuterClass.MyMessageWrapper parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.piotr.wera.MyMessageOuterClass.MyMessageWrapper parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.piotr.wera.MyMessageOuterClass.MyMessageWrapper parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.piotr.wera.MyMessageOuterClass.MyMessageWrapper parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.piotr.wera.MyMessageOuterClass.MyMessageWrapper parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.piotr.wera.MyMessageOuterClass.MyMessageWrapper parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.piotr.wera.MyMessageOuterClass.MyMessageWrapper parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.piotr.wera.MyMessageOuterClass.MyMessageWrapper parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static me.piotr.wera.MyMessageOuterClass.MyMessageWrapper parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.piotr.wera.MyMessageOuterClass.MyMessageWrapper parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.piotr.wera.MyMessageOuterClass.MyMessageWrapper parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(me.piotr.wera.MyMessageOuterClass.MyMessageWrapper prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code me.piotr.wera.MyMessageWrapper}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:me.piotr.wera.MyMessageWrapper)
        me.piotr.wera.MyMessageOuterClass.MyMessageWrapperOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return me.piotr.wera.MyMessageOuterClass.internal_static_me_piotr_wera_MyMessageWrapper_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return me.piotr.wera.MyMessageOuterClass.internal_static_me_piotr_wera_MyMessageWrapper_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                me.piotr.wera.MyMessageOuterClass.MyMessageWrapper.class, me.piotr.wera.MyMessageOuterClass.MyMessageWrapper.Builder.class);
      }

      // Construct using me.piotr.wera.MyMessageOuterClass.MyMessageWrapper.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMessagesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (messagesBuilder_ == null) {
          messages_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          messagesBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.piotr.wera.MyMessageOuterClass.internal_static_me_piotr_wera_MyMessageWrapper_descriptor;
      }

      @java.lang.Override
      public me.piotr.wera.MyMessageOuterClass.MyMessageWrapper getDefaultInstanceForType() {
        return me.piotr.wera.MyMessageOuterClass.MyMessageWrapper.getDefaultInstance();
      }

      @java.lang.Override
      public me.piotr.wera.MyMessageOuterClass.MyMessageWrapper build() {
        me.piotr.wera.MyMessageOuterClass.MyMessageWrapper result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public me.piotr.wera.MyMessageOuterClass.MyMessageWrapper buildPartial() {
        me.piotr.wera.MyMessageOuterClass.MyMessageWrapper result = new me.piotr.wera.MyMessageOuterClass.MyMessageWrapper(this);
        int from_bitField0_ = bitField0_;
        if (messagesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            messages_ = java.util.Collections.unmodifiableList(messages_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.messages_ = messages_;
        } else {
          result.messages_ = messagesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.piotr.wera.MyMessageOuterClass.MyMessageWrapper) {
          return mergeFrom((me.piotr.wera.MyMessageOuterClass.MyMessageWrapper)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(me.piotr.wera.MyMessageOuterClass.MyMessageWrapper other) {
        if (other == me.piotr.wera.MyMessageOuterClass.MyMessageWrapper.getDefaultInstance()) return this;
        if (messagesBuilder_ == null) {
          if (!other.messages_.isEmpty()) {
            if (messages_.isEmpty()) {
              messages_ = other.messages_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMessagesIsMutable();
              messages_.addAll(other.messages_);
            }
            onChanged();
          }
        } else {
          if (!other.messages_.isEmpty()) {
            if (messagesBuilder_.isEmpty()) {
              messagesBuilder_.dispose();
              messagesBuilder_ = null;
              messages_ = other.messages_;
              bitField0_ = (bitField0_ & ~0x00000001);
              messagesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMessagesFieldBuilder() : null;
            } else {
              messagesBuilder_.addAllMessages(other.messages_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        me.piotr.wera.MyMessageOuterClass.MyMessageWrapper parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (me.piotr.wera.MyMessageOuterClass.MyMessageWrapper) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<me.piotr.wera.MyMessageOuterClass.MyMessage> messages_ =
        java.util.Collections.emptyList();
      private void ensureMessagesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          messages_ = new java.util.ArrayList<me.piotr.wera.MyMessageOuterClass.MyMessage>(messages_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          me.piotr.wera.MyMessageOuterClass.MyMessage, me.piotr.wera.MyMessageOuterClass.MyMessage.Builder, me.piotr.wera.MyMessageOuterClass.MyMessageOrBuilder> messagesBuilder_;

      /**
       * <code>repeated .me.piotr.wera.MyMessage messages = 1;</code>
       */
      public java.util.List<me.piotr.wera.MyMessageOuterClass.MyMessage> getMessagesList() {
        if (messagesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(messages_);
        } else {
          return messagesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .me.piotr.wera.MyMessage messages = 1;</code>
       */
      public int getMessagesCount() {
        if (messagesBuilder_ == null) {
          return messages_.size();
        } else {
          return messagesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .me.piotr.wera.MyMessage messages = 1;</code>
       */
      public me.piotr.wera.MyMessageOuterClass.MyMessage getMessages(int index) {
        if (messagesBuilder_ == null) {
          return messages_.get(index);
        } else {
          return messagesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .me.piotr.wera.MyMessage messages = 1;</code>
       */
      public Builder setMessages(
          int index, me.piotr.wera.MyMessageOuterClass.MyMessage value) {
        if (messagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessagesIsMutable();
          messages_.set(index, value);
          onChanged();
        } else {
          messagesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .me.piotr.wera.MyMessage messages = 1;</code>
       */
      public Builder setMessages(
          int index, me.piotr.wera.MyMessageOuterClass.MyMessage.Builder builderForValue) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          messages_.set(index, builderForValue.build());
          onChanged();
        } else {
          messagesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .me.piotr.wera.MyMessage messages = 1;</code>
       */
      public Builder addMessages(me.piotr.wera.MyMessageOuterClass.MyMessage value) {
        if (messagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessagesIsMutable();
          messages_.add(value);
          onChanged();
        } else {
          messagesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .me.piotr.wera.MyMessage messages = 1;</code>
       */
      public Builder addMessages(
          int index, me.piotr.wera.MyMessageOuterClass.MyMessage value) {
        if (messagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessagesIsMutable();
          messages_.add(index, value);
          onChanged();
        } else {
          messagesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .me.piotr.wera.MyMessage messages = 1;</code>
       */
      public Builder addMessages(
          me.piotr.wera.MyMessageOuterClass.MyMessage.Builder builderForValue) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          messages_.add(builderForValue.build());
          onChanged();
        } else {
          messagesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .me.piotr.wera.MyMessage messages = 1;</code>
       */
      public Builder addMessages(
          int index, me.piotr.wera.MyMessageOuterClass.MyMessage.Builder builderForValue) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          messages_.add(index, builderForValue.build());
          onChanged();
        } else {
          messagesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .me.piotr.wera.MyMessage messages = 1;</code>
       */
      public Builder addAllMessages(
          java.lang.Iterable<? extends me.piotr.wera.MyMessageOuterClass.MyMessage> values) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, messages_);
          onChanged();
        } else {
          messagesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .me.piotr.wera.MyMessage messages = 1;</code>
       */
      public Builder clearMessages() {
        if (messagesBuilder_ == null) {
          messages_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          messagesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .me.piotr.wera.MyMessage messages = 1;</code>
       */
      public Builder removeMessages(int index) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          messages_.remove(index);
          onChanged();
        } else {
          messagesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .me.piotr.wera.MyMessage messages = 1;</code>
       */
      public me.piotr.wera.MyMessageOuterClass.MyMessage.Builder getMessagesBuilder(
          int index) {
        return getMessagesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .me.piotr.wera.MyMessage messages = 1;</code>
       */
      public me.piotr.wera.MyMessageOuterClass.MyMessageOrBuilder getMessagesOrBuilder(
          int index) {
        if (messagesBuilder_ == null) {
          return messages_.get(index);  } else {
          return messagesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .me.piotr.wera.MyMessage messages = 1;</code>
       */
      public java.util.List<? extends me.piotr.wera.MyMessageOuterClass.MyMessageOrBuilder> 
           getMessagesOrBuilderList() {
        if (messagesBuilder_ != null) {
          return messagesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(messages_);
        }
      }
      /**
       * <code>repeated .me.piotr.wera.MyMessage messages = 1;</code>
       */
      public me.piotr.wera.MyMessageOuterClass.MyMessage.Builder addMessagesBuilder() {
        return getMessagesFieldBuilder().addBuilder(
            me.piotr.wera.MyMessageOuterClass.MyMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .me.piotr.wera.MyMessage messages = 1;</code>
       */
      public me.piotr.wera.MyMessageOuterClass.MyMessage.Builder addMessagesBuilder(
          int index) {
        return getMessagesFieldBuilder().addBuilder(
            index, me.piotr.wera.MyMessageOuterClass.MyMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .me.piotr.wera.MyMessage messages = 1;</code>
       */
      public java.util.List<me.piotr.wera.MyMessageOuterClass.MyMessage.Builder> 
           getMessagesBuilderList() {
        return getMessagesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          me.piotr.wera.MyMessageOuterClass.MyMessage, me.piotr.wera.MyMessageOuterClass.MyMessage.Builder, me.piotr.wera.MyMessageOuterClass.MyMessageOrBuilder> 
          getMessagesFieldBuilder() {
        if (messagesBuilder_ == null) {
          messagesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              me.piotr.wera.MyMessageOuterClass.MyMessage, me.piotr.wera.MyMessageOuterClass.MyMessage.Builder, me.piotr.wera.MyMessageOuterClass.MyMessageOrBuilder>(
                  messages_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          messages_ = null;
        }
        return messagesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:me.piotr.wera.MyMessageWrapper)
    }

    // @@protoc_insertion_point(class_scope:me.piotr.wera.MyMessageWrapper)
    private static final me.piotr.wera.MyMessageOuterClass.MyMessageWrapper DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new me.piotr.wera.MyMessageOuterClass.MyMessageWrapper();
    }

    public static me.piotr.wera.MyMessageOuterClass.MyMessageWrapper getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MyMessageWrapper>
        PARSER = new com.google.protobuf.AbstractParser<MyMessageWrapper>() {
      @java.lang.Override
      public MyMessageWrapper parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MyMessageWrapper(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MyMessageWrapper> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MyMessageWrapper> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public me.piotr.wera.MyMessageOuterClass.MyMessageWrapper getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_me_piotr_wera_MyMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_me_piotr_wera_MyMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_me_piotr_wera_MyMessageWrapper_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_me_piotr_wera_MyMessageWrapper_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017MyMessage.proto\022\rme.piotr.wera\032\021Contex" +
      "tEnum.proto\032\037google/protobuf/timestamp.p" +
      "roto\"\265\001\n\tMyMessage\022\014\n\004name\030\001 \001(\t\022\017\n\007numb" +
      "ers\030\002 \003(\005\022+\n\007context\030\003 \001(\0162\032.me.piotr.we" +
      "ra.ContextEnum\022-\n\ttimestamp\030\004 \001(\0132\032.goog" +
      "le.protobuf.Timestamp\022\020\n\006value1\030\005 \001(\tH\000\022" +
      "\020\n\006value2\030\006 \001(\005H\000B\t\n\007variant\">\n\020MyMessag" +
      "eWrapper\022*\n\010messages\030\001 \003(\0132\030.me.piotr.we" +
      "ra.MyMessageb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          me.piotr.wera.ContextEnumOuterClass.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_me_piotr_wera_MyMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_me_piotr_wera_MyMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_me_piotr_wera_MyMessage_descriptor,
        new java.lang.String[] { "Name", "Numbers", "Context", "Timestamp", "Value1", "Value2", "Variant", });
    internal_static_me_piotr_wera_MyMessageWrapper_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_me_piotr_wera_MyMessageWrapper_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_me_piotr_wera_MyMessageWrapper_descriptor,
        new java.lang.String[] { "Messages", });
    me.piotr.wera.ContextEnumOuterClass.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
